---
  kind: "ConfigMap"
  apiVersion: "v1"
  metadata:
    name: "platform"
    labels:
      id: "platform"
  data:
    domain: "example.com"
    tap-version: "0.8"
    cli-version: "0.8"
    core-organization: "trustedanalytics-ng"
---
  kind: "ConfigMap"
  apiVersion: "v1"
  metadata: 
    name: "catalog-credentials"
    labels: 
      id: "catalog-credentials"
  data: 
    catalog-port: "80"
    catalog-user: "admin"
    catalog-pass: "password"
    catalog-ssl-cert-file-location: ""
    catalog-ssl-key-file-location: ""
    catalog-ssl-ca-file-location: ""
    insecure-skip-verify: "true"
    broker-log-level: "DEBUG"
