# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
  kind: "Deployment"
  apiVersion: "extensions/v1beta1"
  metadata: 
    name: "catalog"
  spec: 
    replicas: 1
    selector: 
      matchLabels: 
        id: "catalog"
    template: 
      metadata: 
        labels: 
          id: "catalog"
      spec: 
        containers: 
          - 
            name: "etcdcatalog"
            image: "quay.io/coreos/etcd:v3.0.10"
            ports: 
              - 
                containerPort: 2379
                protocol: "TCP"
            imagePullPolicy: "IfNotPresent"
          - 
            name: "catalog"
            image: "tap-catalog"
            ports:
              - 
                containerPort: 80
                protocol: "TCP"
            env: 
              - name: "CORE_ORGANIZATION"
                valueFrom:
                  configMapKeyRef:
                    name: "platform"
                    key: "core-organization"
              -
                name: "CATALOG_PORT"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-port"
              - 
                name: "CATALOG_USER"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-user"
              - 
                name: "CATALOG_PASS"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-pass"
              - 
                name: "CATALOG_SSL_CERT_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-cert-file-location"
              - 
                name: "CATALOG_SSL_KEY_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-key-file-location"
              - 
                name: "CATALOG_SSL_CA_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-ca-file-location"
              - 
                name: "INSECURE_SKIP_VERIFY"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "insecure-skip-verify"
              - 
                name: "BROKER_LOG_LEVEL"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "broker-log-level"
            imagePullPolicy: "IfNotPresent"
        restartPolicy: "Always"
        dnsPolicy: "ClusterFirst"
