---
  kind: "Deployment"
  apiVersion: "extensions/v1beta1"
  metadata: 
    name: "catalog"
  spec: 
    replicas: 1
    selector: 
      matchLabels: 
        id: "catalog"
    template: 
      metadata: 
        labels: 
          id: "catalog"
      spec: 
        containers: 
          - 
            name: "etcdcatalog"
            image: "quay.io/coreos/etcd:latest"
            ports: 
              - 
                containerPort: 2379
                protocol: "TCP"
            imagePullPolicy: "IfNotPresent"
          - 
            name: "catalog"
            image: "tap-catalog"
            ports: 
              - 
                containerPort: 8083
                protocol: "TCP"
            env: 
              - 
                name: "CATALOG_PORT"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-port"
              - 
                name: "CATALOG_USER"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-user"
              - 
                name: "CATALOG_PASS"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-pass"
              - 
                name: "CATALOG_SSL_CERT_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-cert-file-location"
              - 
                name: "CATALOG_SSL_KEY_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-key-file-location"
              - 
                name: "CATALOG_SSL_CA_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "catalog-ssl-ca-file-location"
              - 
                name: "INSECURE_SKIP_VERIFY"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "insecure-skip-verify"
              - 
                name: "BROKER_LOG_LEVEL"
                valueFrom: 
                  configMapKeyRef: 
                    name: "catalog-credentials"
                    key: "broker-log-level"
            imagePullPolicy: "IfNotPresent"
        restartPolicy: "Always"
        dnsPolicy: "ClusterFirst"
