// Automatically generated by MockGen. DO NOT EDIT!
// Source: data/data_repository.go

package data

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of RepositoryApi interface
type MockRepositoryApi struct {
	ctrl     *gomock.Controller
	recorder *_MockRepositoryApiRecorder
}

// Recorder for MockRepositoryApi (not exported)
type _MockRepositoryApiRecorder struct {
	mock *MockRepositoryApi
}

func NewMockRepositoryApi(ctrl *gomock.Controller) *MockRepositoryApi {
	mock := &MockRepositoryApi{ctrl: ctrl}
	mock.recorder = &_MockRepositoryApiRecorder{mock}
	return mock
}

func (_m *MockRepositoryApi) EXPECT() *_MockRepositoryApiRecorder {
	return _m.recorder
}

func (_m *MockRepositoryApi) StoreData(keyStore map[string]interface{}) error {
	ret := _m.ctrl.Call(_m, "StoreData", keyStore)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRepositoryApiRecorder) StoreData(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StoreData", arg0)
}

func (_m *MockRepositoryApi) UpdateData(updates []PatchSingleUpdate) error {
	ret := _m.ctrl.Call(_m, "UpdateData", updates)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRepositoryApiRecorder) UpdateData(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateData", arg0)
}

func (_m *MockRepositoryApi) ApplyPatchedValues(patchedKeyValues PatchedKeyValues) error {
	ret := _m.ctrl.Call(_m, "ApplyPatchedValues", patchedKeyValues)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRepositoryApiRecorder) ApplyPatchedValues(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ApplyPatchedValues", arg0)
}

func (_m *MockRepositoryApi) DeleteData(key string) error {
	ret := _m.ctrl.Call(_m, "DeleteData", key)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRepositoryApiRecorder) DeleteData(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteData", arg0)
}

func (_m *MockRepositoryApi) GetData(key string, model interface{}) (interface{}, error) {
	ret := _m.ctrl.Call(_m, "GetData", key, model)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRepositoryApiRecorder) GetData(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetData", arg0, arg1)
}

func (_m *MockRepositoryApi) GetListOfData(key string, model interface{}) ([]interface{}, error) {
	ret := _m.ctrl.Call(_m, "GetListOfData", key, model)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRepositoryApiRecorder) GetListOfData(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetListOfData", arg0, arg1)
}

func (_m *MockRepositoryApi) GetListOfDataFlat(key string, model interface{}) ([]interface{}, error) {
	ret := _m.ctrl.Call(_m, "GetListOfDataFlat", key, model)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRepositoryApiRecorder) GetListOfDataFlat(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetListOfDataFlat", arg0, arg1)
}

func (_m *MockRepositoryApi) GetDataCounter(key string, model interface{}) (int, error) {
	ret := _m.ctrl.Call(_m, "GetDataCounter", key, model)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRepositoryApiRecorder) GetDataCounter(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetDataCounter", arg0, arg1)
}

func (_m *MockRepositoryApi) CreateDirs(org string) error {
	ret := _m.ctrl.Call(_m, "CreateDirs", org)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRepositoryApiRecorder) CreateDirs(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateDirs", arg0)
}

func (_m *MockRepositoryApi) IsExistByName(expectedName string, model interface{}, key string) (bool, error) {
	ret := _m.ctrl.Call(_m, "IsExistByName", expectedName, model, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRepositoryApiRecorder) IsExistByName(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsExistByName", arg0, arg1, arg2)
}
